const APP={brand:'FERROFORMA',visitFee:9990,calBookingUrl:'',domain:'https://TU-DOMINIO.CL',baseM2:118000};
const state={width:4,height:1.8,material:'20x20',style:'vertical',density:2,top:'straight',access:'none',finish:'primer',color:'#1d2422'};
const mult={material:{'20x20':1,'30x30':1.14,'40x20':1.20,pletina:.94},style:{vertical:1,horizontal:1.07,geometric:1.28,diagonal:1.20,privacy:1.34,industrial:1.12},density:{1:.88,2:1,3:1.18},finish:{primer:1,premium:1.08,galvanized:1.25,raw:.88},access:{none:0,pedestrian:145000,sliding:520000,double:430000}};
const fmt=n=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Math.round(n/1000)*1000);const one=n=>Number(n).toLocaleString('es-CL',{minimumFractionDigits:1,maximumFractionDigits:1});
function estimate(){const area=state.width*state.height;const densityM=mult.density[state.density];const core=area*APP.baseM2*mult.material[state.material]*mult.style[state.style]*densityM*mult.finish[state.finish]+mult.access[state.access];const complexity=state.style==='geometric'||state.style==='privacy'||state.density===3?'Alta':state.style==='diagonal'||state.access!=='none'?'Media-alta':'Media';const min=core*.90,max=core*1.12;return{area,core,min,max,complexity}}
function setText(){const e=estimate();document.getElementById('outWidth').textContent=one(state.width)+' m';document.getElementById('outHeight').textContent=one(state.height)+' m';document.getElementById('outDensity').textContent=['','Aireada','Media','Cerrada'][state.density];document.getElementById('area').textContent=one(e.area)+' m²';document.getElementById('complexity').textContent=e.complexity;document.getElementById('priceRange').textContent=`${fmt(e.min)} – ${fmt(e.max)}`;document.getElementById('range2').textContent=`${fmt(e.min)} – ${fmt(e.max)}`;document.getElementById('designTitle').textContent=`Reja ${label('style',state.style).toLowerCase()} · ${one(state.width)} × ${one(state.height)} m`;document.getElementById('legendMaterial').textContent='Perfil '+label('material',state.material);document.getElementById('legendStyle').textContent=label('style',state.style);document.getElementById('legendFinish').textContent=document.getElementById('finish').selectedOptions[0].textContent;document.getElementById('accessLabel').textContent=state.access==='none'?'No':document.getElementById('access').selectedOptions[0].textContent.replace('+ ','')}
function label(group,val){const el=document.querySelector(`[data-group="${group}"] [data-value="${val}"]`);return el?el.textContent:val}
function renderGate(){const W=900,H=260,pad=14,rail=10;let s=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none" aria-label="Vista del diseño de reja"><rect x="0" y="0" width="${W}" height="${H}" fill="none"/>`;const c=state.color;s+=`<rect x="5" y="7" width="${W-10}" height="${H-14}" rx="3" fill="none" stroke="${c}" stroke-width="14"/>`;
 const count=state.density===1?12:state.density===2?18:26;if(state.style==='vertical'||state.style==='industrial'||state.style==='privacy'){for(let i=1;i<count;i++){const x=pad+i*(W-2*pad)/count;const sw=state.style==='privacy'?18:state.style==='industrial'?11:7;s+=`<line x1="${x}" y1="12" x2="${x}" y2="${H-12}" stroke="${c}" stroke-width="${sw}"/>`;if(state.top==='spear')s+=`<polygon points="${x-7},14 ${x},0 ${x+7},14" fill="${c}"/>`}}
 if(state.style==='horizontal'||state.style==='industrial'){const rows=state.density===1?6:state.density===2?9:13;for(let i=1;i<rows;i++){const y=pad+i*(H-2*pad)/rows;s+=`<line x1="10" y1="${y}" x2="${W-10}" y2="${y}" stroke="${c}" stroke-width="${state.style==='industrial'?9:7}"/>`}}
 if(state.style==='diagonal'||state.style==='geometric'){for(let x=-H;x<W;x+=state.density===3?45:70)s+=`<line x1="${x}" y1="${H}" x2="${x+H}" y2="0" stroke="${c}" stroke-width="7"/>`;if(state.style==='geometric')for(let x=0;x<W;x+=130)s+=`<polygon points="${x},130 ${x+65},60 ${x+130},130 ${x+65},200" fill="none" stroke="${c}" stroke-width="6"/>`}
 if(state.top==='arc')s+=`<path d="M 8 24 Q ${W/2} -32 ${W-8} 24" fill="none" stroke="${c}" stroke-width="12"/>`;if(state.access!=='none'){const x=state.access==='pedestrian'?W*.68:W*.50;const w=state.access==='pedestrian'?W*.20:W*.42;s+=`<rect x="${x}" y="8" width="${w}" height="${H-16}" fill="none" stroke="#d7ff59" stroke-width="7"/><circle cx="${x+20}" cy="${H/2}" r="7" fill="#d7ff59"/>`}s+=`</svg>`;document.getElementById('svgWrap').innerHTML=s}
function update(){setText();renderGate();sessionStorage.setItem('gateDesign',JSON.stringify({...state,estimate:estimate()}))}
document.getElementById('width').oninput=e=>{state.width=+e.target.value;update()};document.getElementById('height').oninput=e=>{state.height=+e.target.value;update()};document.getElementById('density').oninput=e=>{state.density=+e.target.value;update()};document.getElementById('access').onchange=e=>{state.access=e.target.value;update()};document.getElementById('finish').onchange=e=>{state.finish=e.target.value;update()};document.querySelectorAll('[data-group]').forEach(g=>g.addEventListener('click',e=>{const b=e.target.closest('.choice');if(!b)return;e.preventDefault();g.querySelectorAll('.choice').forEach(x=>x.classList.remove('active'));b.classList.add('active');state[g.dataset.group]=b.dataset.value;update()}));
function client(){return{name:clientName.value.trim(),phone:clientPhone.value.trim(),email:clientEmail.value.trim(),commune:clientCommune.value.trim(),address:clientAddress.value.trim(),note:clientNote.value.trim()}}
document.getElementById('payBtn').onclick=async()=>{const c=client();if(!c.name||!c.phone||!c.email||!c.commune)return alert('Completa nombre, WhatsApp, correo y comuna para continuar.');sessionStorage.setItem('gateClient',JSON.stringify(c));const btn=document.getElementById('payBtn');btn.disabled=true;btn.textContent='Preparando pago…';try{const payload={amount:APP.visitFee,customer:c,design:{...state,estimate:estimate()},returnUrl:location.origin+location.pathname};const r=await fetch('/api/create-payment',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||'No se pudo iniciar el pago');location.href=d.init_point||d.demo_url}catch(e){alert(e.message+'\n\nSi estás abriendo el HTML directamente, despliega en Vercel para activar el backend de pago.');btn.disabled=false;btn.textContent='Pagar y elegir horario →'}};
async function handleReturn(){const q=new URLSearchParams(location.search);const p=q.get('payment');if(!p)return;if(p==='demo-approved'){unlock();history.replaceState({},'',location.pathname+'#reserva');return}const id=q.get('payment_id')||q.get('collection_id');if((p==='success'||q.get('status')==='approved')&&id){try{const r=await fetch('/api/payment-status?id='+encodeURIComponent(id));const d=await r.json();if(d.approved){unlock();history.replaceState({},'',location.pathname+'#reserva')}}catch(e){console.warn(e)}}}
function unlock(){document.getElementById('unlocked').classList.add('on');const c=JSON.parse(sessionStorage.getItem('gateClient')||'{}');const frame=document.getElementById('calFrame'),demo=document.getElementById('demoVisitSlots');if(APP.calBookingUrl){const u=new URL(APP.calBookingUrl);if(c.name)u.searchParams.set('name',c.name);if(c.email)u.searchParams.set('email',c.email);frame.innerHTML=`<iframe src="${u}" title="Agenda visita técnica" style="width:100%;height:690px;border:0;border-radius:14px;background:white" loading="lazy"></iframe>`}else{document.getElementById('calHint').textContent='Modo demo: configura APP.calBookingUrl para usar disponibilidad real.';demo.innerHTML=['Mar 09:00','Mar 15:30','Mié 11:00','Jue 16:00'].map(x=>`<button class="slot" onclick="alert('Demo: ${x}. En producción se reserva desde Cal.com.')">${x}</button>`).join('')}location.hash='reserva'}
update();handleReturn();
